apiVersion: v1
kind: Service
metadata:
  name: bitwarden-service
spec:
  selector:
    app: bitwarden.name
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.externalPort }}
      targetPort: {{ .Values.app.service.internalPort }}
      nodePort: {{ .Values.app.service.nodePort }}
  type: {{ .Values.app.service.type }}
