apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  containers:
  - name: busybox
    image: 609244884738.dkr.ecr.eu-west-1.amazonaws.com/busybox:latest
