apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-deployment
  labels:
    app: bitwarden
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
        - name: bitwarden
          image: 609244884738.dkr.ecr.eu-west-1.amazonaws.com/bitwarden
          ports:
            - containerPort: 443
