apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  labels:
    run: bitwarden
spec:
  type: NodePort
  ports:
  - port: 80
    targetport: 80
    protocol: TCP
    name: bitwarden
  selector:
    run: bitwarden
