kind: Service
apiVersion: v1
metadata:
  name: bitwarden-service
spec:
  selector:
    app: bitwarden
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort